### ISSUE TITLE
Blank screen on level up

### ISSUE THREAD

**Issue by Phiddlestixx** [geoidesic/foundryvtt-actor-studio#100]
Created a new character with Actor Studio using DDB imported compendiums and the SRD compendium.  When attempting to level up, i manually entered the XP onto the Tidy 5e sheet and level up button appeared.  

Actor Studio pops up with a blank screen.  Happens on both custom and SRD compendium.  Error also appears on console, posted under this pic.

Currently on Foundry v12.331 and using Actor Studio 1.5.3
![image](https://github.com/user-attachments/assets/96bd096d-3e80-4d60-ac6a-3940f370f661)

![image](https://github.com/user-attachments/assets/980c4c0d-0a46-4813-8daf-4f2fe0885aa8)

**Comment by geoidesic** [comment]
fixed in v1.5.4

**Comment by Phiddlestixx** [comment]
Still having same issue on 1.5.4.  Uninstalled and reinstalled.  Same error in console as well.

**Comment by geoidesic** [comment]
Did you clear your browser cache?
