### ISSUE TITLE
Stopping mid advancments breaks Multi Choice

### ISSUE THREAD

**Issue by Zarhog** [geoidesic/foundryvtt-actor-studio#104]
I cound that if you stop the character creation mid advancemnt and lose the window out, then start a new character, some multiple choices are skipped and others lack the check boxes/buttons and  next button.

**Comment by geoidesic** [comment]
I'd need the data for the selections that were made in order to look into this.

**Comment by geoidesic** [comment]
This also relates to #81

**Comment by Zarhog** [comment]
unfortunately i don't know the exact steps, as I stumbled across this one by accident

**Comment by geoidesic** [comment]
Ok then I'm going to close this, as there's nothing I can do if I can't replicate the issue. If you can find a way to replicate it reliably, please re-open it.
