### ISSUE TITLE
Are there any plans for adding other source books?

### ISSUE THREAD

**Issue by CorradoJPetruzzelli** [geoidesic/foundryvtt-actor-studio#106]
I really like character creation tools in the engine I'm working with, but this only has SRD content. Is there any way to get the other source books to work with this or plans for adding other source book material?

Even adding a tutorial on how its done would be nice.

**Comment by geoidesic** [comment]
Hi. Thanks for your interest in Actor Studio.

Please note that the Actor Studio does not provide access to content. It only allows you to link any content that is in your game. FoundryVTT now has a dnd5e license, so presumably they are working on porting many of the 5e products into the FoundryVTT ecosystem. However, the ball is in their court on that front. 

There are some tools that allow you to export data from dndbeyond if you have access to that: https://foundryvtt.com/packages/ddb-importer which is one way to get that content into your game, at which point you'd be able to link it to Actor Studio.
