### ISSUE TITLE
Advancments not working

### ISSUE THREAD

**Issue by Zarhog** [geoidesic/foundryvtt-actor-studio#113]
Short explination: once all selections are done in the initial screen the automation is not working (as in its not taking you though the creation steps, its just remaining on the screen

but dose not work on the player side
after  testing it dose not work on eather player or GM side
worked on GM side but not player prior to update

https://github.com/user-attachments/assets/fce7bdcf-ba0c-48ba-9fa9-350dfda3e1c8

**Comment by geoidesic** [comment]
This is because the background `Acolyte` being used has no advancements. If AS finds no advancements then it can't complete. 

@todo: make it more robust if possible.
