### ISSUE TITLE
Compatability issue with System Customizer Module

### ISSUE THREAD

**Issue by ChobitsCrazy** [geoidesic/foundryvtt-actor-studio#50]
Foundry - v11.315
D&D5e - 3.1.2
AS - 1.0
System Customizer - 2.0.7
Modules - Only modules enabled are AS and System Customizer

Steps to recreate the issue:
1. Activate both modules
2. Modify Settings for System Customizer
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/b1fdc226-2b92-45f6-9b92-b17f0e9ee12f)
3. Create new actor, option to fill in ability scores is missing:
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/62b9e196-9883-4f55-8772-be05f41699ba)

**Comment by geoidesic** [comment]
Unfortunately that is a premium module (System Customiser) so I can't install it to have a look.
If you open the browser inspector you can screenshot any errors in the console. Might be a simple fix. Don't know.

Also try enabling all the rolling options and see if you get different behaviour.

**Comment by ChobitsCrazy** [comment]
Presents the same, and cannot make any selections in the dropdown.
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/8a5d02e5-90f0-401e-9202-b842a65d5b41)

I noticed these:
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/da0364fc-7f2c-4fd3-80eb-8d30cb055813)

Also get this:
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/5346d91c-b84c-4714-b310-8bc57ae6327f)

**Comment by geoidesic** [comment]
Which browser?

**Comment by ChobitsCrazy** [comment]
Edge

**Comment by geoidesic** [comment]
Check the Network tab of the inspector for any 404 errors.
Also try browse to https://foundryvtt.3dmentia.com/modules/foundryvtt-actor-studio/dist/ManualEntry-Cencm6oc.js (replace the domain with your domain).

**Comment by geoidesic** [comment]
Try it without the premium module, that way we can at least rule that in or out.

**Comment by ChobitsCrazy** [comment]
Yeah when System Customizer is disabled it works fine.
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/b7eb90bd-0e2b-4e9a-ab1c-f599447058d3)

If I do:
http://[localhost:30000/modules/foundryvtt-actor-studio/dist/ManualEntry-Cencm6oc.js](http://localhost:30000/modules/foundryvtt-actor-studio/dist/ManualEntry-Cencm6oc.js)
It works okay

**Comment by geoidesic** [comment]
Very strange. I don't know what System Customiser does but from the error message you showed it looks like it's preventing the required Actor Studio .js files from being imported. I'm not even sure how it's able to do that.

**Comment by ChobitsCrazy** [comment]
I'll check with Ripper

**Comment by geoidesic** [comment]
I've pinged him too, with a link to this ticket.

**Comment by geoidesic** [comment]
@ChobitsCrazy any news on this?

**Comment by ChobitsCrazy** [comment]
Not yet, Ripper has pushed out updates and the latest is on v12 however I cannot move over to v12 yet due to other modules lagging behind. Once I'm able to move over to v12 I'll be able to update and make sure this is still an issue and then report it to Ripper.

**Comment by Steve-LP** [comment]
I can confirm the same error when adding this to my DnD 5e variant "Lord of the Rings" from Free League. There is a community plugin that implements the major rule changes (but no backgrounds, classes etc.) - https://github.com/ZWinther/lotr5e-module

If I deactivate it, Actor Studio works like a charm. Not sure if that is helpful to trace down the issue.

**Comment by geoidesic** [comment]
Fixed in https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.3.3
