### ISSUE TITLE
Changing Actor name in popout interface does not reflect after creation

### ISSUE THREAD

**Issue by ChobitsCrazy** [geoidesic/foundryvtt-actor-studio#51]
Foundry - v11.315
D&D5e - 3.1.2
AS - 1.0
Modules - Only modules enabled is AS

1. Create an actor with AS with name A
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/b4e8fbd6-bd12-44c5-ab35-7dde1fef3019)
2. Update the character name in the interface.
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/3a0bd98a-618e-4e28-8a7e-97e9abafdf58)
3. Finish actor creation and the actor's name is not B as expected.
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/27ad4697-9962-4ca7-8bc3-d007de552872)

**Comment by geoidesic** [comment]
Fixed in https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.0.3
