### ISSUE TITLE
Preemptive end of character creation.

### ISSUE THREAD

**Issue by ChobitsCrazy** [geoidesic/foundryvtt-actor-studio#52]
Foundry - v11.315
D&D5e - 3.1.2
AS - 1.0
Modules - Only modules enabled is AS

After selecting race/background/class and going through the advancement. Once the Background advancement is competed it ends the character creation and preemptively creates the character.
https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/d12114f9-842d-42c9-a5e6-36bc8a190baf

**Comment by geoidesic** [comment]
To debug this I'd either need any errors from the console or I'd need access to the data that you are using... class, subclass, background, race

**Comment by ChobitsCrazy** [comment]
Let me know if this helps:
[fvtt-Item-path-of-the-ancestral-guardian-0YmLPWfKyg4prYaP.json](https://github.com/user-attachments/files/15997581/fvtt-Item-path-of-the-ancestral-guardian-0YmLPWfKyg4prYaP.json)
[fvtt-Item-barbarian-QULNqco0htSeBV3e.json](https://github.com/user-attachments/files/15997582/fvtt-Item-barbarian-QULNqco0htSeBV3e.json)
[fvtt-Item-acolyte-ku8oxsYVnmwlfdPF.json](https://github.com/user-attachments/files/15997583/fvtt-Item-acolyte-ku8oxsYVnmwlfdPF.json)
[fvtt-Item-aasimar-csET1gq2IcH8sCwX.json](https://github.com/user-attachments/files/15997584/fvtt-Item-aasimar-csET1gq2IcH8sCwX.json)

**Comment by geoidesic** [comment]
Thanks yes, that does help. It looks like those items are misconfigured. 
I haven't done a full analysis of all those items yet but e.g. the Acolyte that you provided definitely has misconfigured advancements, which is strange because Acolyte background is an SRD item, and the SRD version works correctly... so it begs the questions; 

1. Where did you get the version of Acolyte background that you are using?
2. Why not use the SRD version?

**Comment by geoidesic** [comment]
Further analysis of the Acolyte export you provided...

Here is a side-by-side comparison of the SRC Acolyte, with the version you provided:
![Screenshot 2024-06-27 at 11 29 02](https://github.com/geoidesic/foundryvtt-actor-studio/assets/4637995/2a323689-dd5e-4156-80de-169ef5a6c245)

As you can see, the version you provided (left) has misconfigured advancements.

Most likely this is the case for the other samples you provided too.

**Comment by ChobitsCrazy** [comment]
So I'll admit that there was a grant items that didn't have any advancement on it, however I fixed those but still have an issue. Here is the advancements for each of these items (most are references to other compendiums):
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/810cf4f5-3404-4e2e-866c-73b8aa43fa69)
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/aec05a5d-333a-4cea-9320-b8d5ed257b5d)
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/372f6b78-e8dd-4ba5-b25c-6f29e0395834)

Would it not be best to detect malformed advancements and just chose to skip over them and continue the process as normal?

**Comment by geoidesic** [comment]
Send me the updated .json files please and I'll see what's possible. I've really just integrated with the 5e advancements system. All Actor Studio does is drops the item on the Actor sheet and then collects the Advancement windows as they popup. If there's one that doesn't pop up, that means that the 5e sheet is experiencing an error and stops the chain. So there's nothing I can do about that.

But what I can do is help you understand where it's breaking and help you work towards understanding how to produce content that is compatible with the dnd5e system.

**Comment by ChobitsCrazy** [comment]
[fvtt-Item-path-of-the-ancestral-guardian-KYB8KhSmf89IEXeI.json](https://github.com/user-attachments/files/16016344/fvtt-Item-path-of-the-ancestral-guardian-KYB8KhSmf89IEXeI.json)
[fvtt-Item-barbarian-yrS4wWNTdnwkyHIr.json](https://github.com/user-attachments/files/16016345/fvtt-Item-barbarian-yrS4wWNTdnwkyHIr.json)
[fvtt-Item-acolyte-Wtvb5gdyEtaYVB0e.json](https://github.com/user-attachments/files/16016346/fvtt-Item-acolyte-Wtvb5gdyEtaYVB0e.json)
[fvtt-Item-aasimar-Tq8mJErlb3U8UHq2.json](https://github.com/user-attachments/files/16016347/fvtt-Item-aasimar-Tq8mJErlb3U8UHq2.json)

**Comment by ChobitsCrazy** [comment]
I'm packing some assets into a test module for better review of the items.

**Comment by ChobitsCrazy** [comment]
[as-test.zip](https://github.com/user-attachments/files/16018339/as-test.zip)

**Comment by geoidesic** [comment]
FYI I tested your new acolyte .json. That worked fine for me. I used it in between SRD choices for the rest and the advancements chained correctly, even though the Item Grants couldn't be processed.

**Comment by ChobitsCrazy** [comment]
So it's failing on the step after the background?

**Comment by ChobitsCrazy** [comment]
Trying each combination of my class/race/etc with the SRD and so far my Half-Elf Race is causing the issue.

**Comment by ChobitsCrazy** [comment]
Created a brand new race with nothing else. Changed the advancement to this and it causes it to end:
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/b1da83de-3d6a-4673-af7f-e5ebb6ecc056)

**Comment by geoidesic** [comment]
Analysed your Aasimar race...

Some good news. I found some errors in Actor Studio logic for processing Advancements. The way it knows whether to continue or stop is it looks at the `level` property of the advancement. My assumption was that it should match the character level, or stop. 

There were two reasons for your Aasimar race to cause a problem:

1. It contains an advancement that has a `level` value of `undefined`, which is wrong.
2. It contains no advancements marked for level `1` (which is why the advancements stopped). However, a level value of `0` is also valid (which it did contain) and should be processed by Actor Studio for Level 1, so that's a bug I can fix. The fact that it worked for all the SRD classes is because all of them have advancements for Level `1`.

I'm not sure how you ended up with an `undefined` level? The system probably shouldn't allow that. However what I'll do is make Actor Studio treat undefined as equivalent to zero, which should act as a bridge for such cases.

**Comment by geoidesic** [comment]
Incidentally I'm a bit confused by why the 5e system allows "Any Level" (i.e. `0`) as an option. It's not clear what the intent there is:
1.  If it's intended for level 1, then why not make it Level 1?
1. If it's intended "any level" then what does that mean? Should it be imported each level? That makes no sense.

**Comment by ChobitsCrazy** [comment]
While the system doesn't inherently allow it, many people will play at level 0 in campaigns (myself included) Since only classes are linked to levels, backgrounds and races aren't a part of the leveling system by default.

NPCs can also have backgrounds and races but never have a class therefore are level 0.

**Comment by geoidesic** [comment]
In that case treating `0` and `undefined` as a proxy for `1` should work. I'll implement that and we'll see.

**Comment by geoidesic** [comment]
Btw FYI Actor Studio drops items in the following order (not in the order they were selected):

1. background
1. race
1. class
1. subclass

So that will always be the order in which the advancements execute.

**Comment by geoidesic** [comment]
Update: the (unreleased) fix I applied worked for the supplied custom class but not for the subclass. Will analyse that next.

**Comment by geoidesic** [comment]
> [as-test.zip](https://github.com/user-attachments/files/16018339/as-test.zip)

FYI some of the item images didn't port

**Comment by geoidesic** [comment]
Fixed in https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.0.2
