### ISSUE TITLE
Debug spam 1.0

### ISSUE THREAD

**Issue by ChobitsCrazy** [geoidesic/foundryvtt-actor-studio#53]
Console gets filled with debugs:
https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/34e4749e-206f-4fcd-866a-8f14c8139c7a

**Comment by geoidesic** [comment]
Thanks will fix in the next release.

**Comment by geoidesic** [comment]
Fixed in https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.0.2

**Comment by ChobitsCrazy** [comment]
This resurfaced in 1.1.0

**Comment by geoidesic** [comment]
Fixed in 1.1.4 again
