### ISSUE TITLE
Subclass not adding to character sheet

### ISSUE THREAD

**Issue by ChobitsCrazy** [geoidesic/foundryvtt-actor-studio#55]
Foundry - v11.315
D&D5e - 3.1.2
AS - 1.0
Modules - Only modules enabled is AS

Subclass not getting added to character sheet (using SRD)
https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/23dd3ff8-e08c-4c7d-8014-0f8d022feb62

Would expect to see it like this:
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/21301107/6cee172e-d1a0-4e4e-bed7-d4c7daa69fdc)

**Comment by ChobitsCrazy** [comment]
Is this also due to the subclass having no advancement at level 1?
If so then:
But it's a forced selection at creation?

**Comment by geoidesic** [comment]
I'll have a look. Probably it's the same problem as #52

**Comment by geoidesic** [comment]
Subclass problem was not related to #52 after all. I think dnd5e system changed something. it was working with system 3.1.2 but with system 3.2.1 I had to take a different approach to getting subclasses all to work.

**Comment by geoidesic** [comment]
Fixed in https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.0.2
