### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by vampiregoat699** [geoidesic/foundryvtt-actor-studio#57]
I get this when trying to make a actor
![image](https://github.com/geoidesic/foundryvtt-actor-studio/assets/124465461/f8a68c3b-6600-4932-a624-e9c81b29c463)

**Comment by ChobitsCrazy** [comment]
Information needed:
Foundry Version?
What system/version?
What module version?
What browser are you using?
What modules are enabled?

**Comment by geoidesic** [comment]
And also if you can open the browser inspector and screen shot any console errors (usually in red). That would help too.

**Comment by vampiregoat699** [comment]
Foundry Version? 12
What system/version? Pc win 11
What module version? only one available is 1.0.3
What browser are you using? Chrome
What modules are enabled? quite a few to list them all
Odd not sure what I did but seems to work fine now

**Comment by geoidesic** [comment]
Ok. For future reference, the question about system wasn't about your computer operating system but about the rpg system you are using on foundry, e.g. dnd5e v3.2.1
