### ISSUE TITLE
Crash and Error when chosing Tiefling from SRD as race

### ISSUE THREAD

**Issue by nschoenwald** [geoidesic/foundryvtt-actor-studio#59]
<img width="425" alt="image" src="https://github.com/geoidesic/foundryvtt-actor-studio/assets/72390280/866f8e46-62ec-473b-8dae-ba6240da0188">

**Comment by geoidesic** [comment]
Fixed in release https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.0.5
