### ISSUE TITLE
Advancments for druid is showing some weird values

### ISSUE THREAD

**Issue by geoidesic** [geoidesic/foundryvtt-actor-studio#62]
1. [x] Weapon Proficiencies
2. [x] Languages
3. [x] Tool Proficiencies
![Screenshot 2024-07-11 at 11 13 36](https://github.com/geoidesic/foundryvtt-actor-studio/assets/4637995/5a7f0661-89b7-4b95-98c3-53234db5ab2a)

**Comment by ChobitsCrazy** [comment]
Wanted to kind of build on this a bit as well with a few items:
1. Size not displaying for race
![image](https://github.com/user-attachments/assets/c8e2a03e-3da3-4e8a-a79e-858448876759)

2. Tooltips for enrichers showing poorly
Regular:
![image](https://github.com/user-attachments/assets/7a47bc8e-e5ef-465c-8bbd-5365824eb380)
AS:
![image](https://github.com/user-attachments/assets/e1208868-8d1c-4a2d-9a23-da044d8c24e2)

3. Choose items not showing any tooltip:
![image](https://github.com/user-attachments/assets/2e6be4ba-7c9b-4b37-a8d6-176092392745)

**Comment by geoidesic** [comment]
@ChobitsCrazy can you add this class to the AS-test module? I'm not seeing that. On mine it's legible.
![Screenshot 2024-07-14 at 11 26 11](https://github.com/user-attachments/assets/a08871b4-f835-414e-b603-55a71ba391f8)

**Comment by geoidesic** [comment]
Closing this. All addressed in [1.1.7](https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.1.7). Let me know if anything isn't working still.

**Comment by ChobitsCrazy** [comment]
Found this one that shows strangely
![image](https://github.com/user-attachments/assets/7ec4212c-131a-43c4-aff4-67957a8989cf)
![image](https://github.com/user-attachments/assets/58191822-8ab6-4fb0-bac4-e1abab4249eb)

**Comment by geoidesic** [comment]
Can you add it to AS-test pls?

**Comment by ChobitsCrazy** [comment]
[as-test.zip](https://github.com/user-attachments/files/16238063/as-test.zip)
Updated the Acolyte background here to have the same advancement

**Comment by geoidesic** [comment]
fixed in [v1.3.2](https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.3.2)
