### ISSUE TITLE
Error on level up for Randal

### ISSUE THREAD

**Issue by ChobitsCrazy** [geoidesic/foundryvtt-actor-studio#63]
AS 1.1.0

Steps to reproduce:
1. Import Randal from SRD starter heroes.
2. Gave him 300 XP
3. Select to level up, get a white screen and error message.
![image](https://github.com/user-attachments/assets/04cdd18a-ed7a-4a8e-8360-8bc1463d1f4d)

**Comment by geoidesic** [comment]
I can't replicate this. Please try it with all other modules disabled.

**Comment by ChobitsCrazy** [comment]
No other modules enabled.
https://github.com/user-attachments/assets/61eeb5aa-d6a9-45a0-ab98-9e4a9116b8b7
[fvtt-Actor-randal-(human-fighter)-ltzSxKpz9hFPOreJ.json](https://github.com/user-attachments/files/16182719/fvtt-Actor-randal-.human-fighter.-ltzSxKpz9hFPOreJ.json)

**Comment by geoidesic** [comment]
What version of foundry and dnd5e?

**Comment by ChobitsCrazy** [comment]
F-v11.315
DnD53-3.1.2

**Comment by ChobitsCrazy** [comment]
I tried with a brand new world and could not recreate the issue. Not really sure what data would cause this issue from any other persistent data.

**Comment by geoidesic** [comment]
It looks like a database indexing issue, so it might have been some sort of transient thing. I'll close this but please re-open it if you can figure out how to reproduce it.

**Comment by ChobitsCrazy** [comment]
Okay I figured out how to recreate the issue. It was actually not enough modules enabled.
If you configure sources to select and those sources are no longer available (via module/compendium) it throws this error message.

**Comment by ChobitsCrazy** [comment]
@geoidesic

**Comment by geoidesic** [comment]
I still cannot replicate this. 

Steps:
1. Use AS to create character using class from `AS-Test`
2. Disable the `AS-test` module
3. Try level up with AS
4. No problem

**Comment by geoidesic** [comment]
> Okay I figured out how to recreate the issue. It was actually not enough modules enabled. If you configure sources to select and those sources are no longer available (via module/compendium) it throws this error message.

I'm confused though. Your OP was about Randal. Randal is part of the dnd5e system, not part of a module. So I'm not sure what source could no longer be available?

What I suggest is, if you are still able to replicate this, write down the precise steps I need to follow in order to recreate this issue.

**Comment by ChobitsCrazy** [comment]
I'll do some more robust testing, try to nail it down 100%.

**Comment by ChobitsCrazy** [comment]
Can't create the error any more so will close this out
