### ISSUE TITLE
Actor creation incomplete at Race

### ISSUE THREAD

**Issue by ChobitsCrazy** [geoidesic/foundryvtt-actor-studio#64]
AS 1.1.0
Foundry: v11.315
DnD5e: v3.1.2

Using the AS-Test module for testing manual character features the character creator is failing at the race step. Also the advancements are opening in a separate window.

https://github.com/user-attachments/assets/51349b06-8609-4678-9c3b-2488ddd29410

**Comment by geoidesic** [comment]
release 1.1.1 fixes the advancement capture issue

**Comment by geoidesic** [comment]
I think the other issue was a result of the same bug. Should be fixed.
