### ISSUE TITLE
### Bug Report: Issue with Subclass Selection

### ISSUE THREAD

**Issue by Zarhog** [geoidesic/foundryvtt-actor-studio#84]
**Title**: Subclass Selection Required at Level 1 for All Classes, Preventing Progression for Classes with Later Subclass Options

**Description**: 
In the "Actor Studio" mod for Foundry VTT, subclass selection is currently enforced at level 1 for all classes. This creates an issue for classes that do not receive their subclass until level 2 or 3, as there is no option to defer this choice. If no subclass is selected at level 1, the character creation process halts at 80%, preventing completion. Additionally, if the mod lacks sources for subclasses, the selection option is hidden, leaving users unable to finalize character creation.

**Expected Behavior**:
- Users should have the option to select "None" during subclass selection at level 1 for classes that receive their subclass at level 2 or 3.
- When the character reaches the appropriate level for subclass selection (e.g., level 2 or 3), the character creator should prompt the user to choose a subclass if "None" was previously selected.
- The character creation process should allow progression without subclass selection at level 1 for applicable classes.

**Actual Behavior**:
- The character creator requires subclass selection at level 1 for all classes, including those that should acquire a subclass at later levels.
- If no subclass is chosen, the character creation process is stuck at 80% and cannot continue.
- If subclass sources are not available, the option to select a subclass is hidden, making it impossible to proceed.

**Steps to Reproduce**:
1. Create a new character using the "Actor Studio" mod.
2. Select a class that typically acquires a subclass at level 2 or 3 (e.g., Fighter, Rogue, Wizard).
3. Attempt to skip subclass selection at level 1.
4. Observe that the character creation process is blocked at 80%.
5. Repeat the process with a class that does not receive subclasses until level 2 or 3, and no subclass sources available.

**Impact**:
This issue blocks users from completing character creation for classes that receive subclasses at higher levels, leading to frustration and incomplete character setups. It also affects users without available subclass sources by preventing progress entirely.

**Suggested Fixes**:
- Add a "None" option for subclass selection at level 1 for classes that receive subclasses at level 2 or 3.
- Implement a prompt to select a subclass when the character reaches the appropriate level if "None" was previously selected.
- Provide a clear message if no subclass sources are available, and allow the character creation process to continue without requiring subclass selection.

**System Information**:
- **Mod Name**: Actor Studio
- **Mod Version**: 1.1.3
- **Foundry VTT Version**: V11 315
- **Operating System**: Linux
- **System Used**: D&D 5e
- **System Version**: 3.3.1

![image](https://github.com/user-attachments/assets/6b54f95c-2e92-4133-8472-77907f5d11f2)

**Comment by geoidesic** [comment]
I think you've made some faulty assumptions about what's happening. 

The fact that the subclass wasn't appearing isn't to do with the levels, it's just a bug that would only manifest under certain weird race conditions.

Hopefully that's been addressed now in release [1.3.4](https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.3.4)

Please check that you have updated to the latest FoundryVTT (v12 stable 330) as there was a bug in their richHTML editor which may have been causing these race conditions in earlier versions of foundry under the following conditions:

If the HTML content for the class contains links to missing compendiums, then it would cause errors which could cause race conditions.

**Comment by geoidesic** [comment]
There

**Comment by geoidesic** [comment]
I'm assuming this is resolved. You can request that I re-open the ticket if not. This may be related to #94
