### ISSUE TITLE
Race and class still not adding

### ISSUE THREAD

**Issue by Zarhog** [geoidesic/foundryvtt-actor-studio#86]
[vtt.tcrdnd.com-1723170175772.log](https://github.com/user-attachments/files/16555116/vtt.tcrdnd.com-1723170175772.log)

https://github.com/user-attachments/assets/43838ac6-9a47-4415-b45a-79c09de7edbd

**Comment by geoidesic** [comment]
@Zarhog Is this now resolved? If so, please close the ticket.
