### ISSUE TITLE
Actor Studio causing formating issues for other Modules

### ISSUE THREAD

**Issue by ChobitsCrazy** [geoidesic/foundryvtt-actor-studio#89]
AS-1.4.1
F-11.315
DnD5e-3.1.2
Other Modules - Rest Recovery for 5E

Causing other config windows from other modules to be jumbled:

https://github.com/user-attachments/assets/ae4c793c-14ea-4bf9-b2fe-f762629c175a

With AS enabled:
![image](https://github.com/user-attachments/assets/6f479601-041e-46c2-a015-6e4ce4898732)

With AS disabled:
![image](https://github.com/user-attachments/assets/a5e17511-8cf4-4877-9ac9-407fe351d7f2)

**Comment by ChobitsCrazy** [comment]
This is still occurring, another example is Item Piles.

**Comment by geoidesic** [comment]
@ChobitsCrazy  did you clear browser cache and install latest version?

**Comment by ChobitsCrazy** [comment]
That is my fault, I thought I was still on the latest version. Everything is still good.
