### ISSUE TITLE
### Bug Report: Cannot Use Standard Array/Point Buy

### ISSUE THREAD

**Issue by deciusaemilius** [geoidesic/foundryvtt-actor-studio#91]
After updating to the latest version, I no longer have the option to control stat allocation using Standard Array or Point Buy:
![image](https://github.com/user-attachments/assets/45288575-bbfa-4d7f-9680-de8759619e20)
![image](https://github.com/user-attachments/assets/0ddaae5a-b9ea-4456-a1ec-8485bfc0adb3)

I can enter stats manually or roll but I can't use the default Standard Array or Point Buy fields.

**Comment by geoidesic** [comment]
I’m looking at the screenshots and not seeing any issues. Can you please be more specific? What do you mean by “can’t use”? As it seems to me you’ve shown screenshots of it being used.

**Comment by deciusaemilius** [comment]
On Standard Array and Point Buy, the number-adjustment section cannot be interacted with in any way. It appears in the drop-down bar, and will carry over the numerical settings. If I manually type numbers in the manual entry box, they will appear on the display 
On the Manual Entry page, I can type in the number field:
![image](https://github.com/user-attachments/assets/5834df11-71a6-4ffe-ae74-e937a71b1aac)
That works like it's supposed to.
If I type in manual numbers and then switch to Standard Array it gives me the option to reset Standard Array:
![image](https://github.com/user-attachments/assets/9edf3b7f-7a1d-4195-87de-af9f35911817)
However once I do so, I can no longer move the standard array numbers. The numbers cannot be further interacted with:
![image](https://github.com/user-attachments/assets/ac9c2109-b83a-4bbc-a861-ae5c6e51cb24)
If I want to move the 15 down to Charisma, I can't do it. There used to be up/down arrows next to each number, allowing the numbers to be moved. That is no longer possible.


The same situation occurs with Point Buy. If I manually enter numbers, it will let me "reset scores"
![image](https://github.com/user-attachments/assets/105e8e02-9ee3-4f06-81d7-8957d252807c)
However, once I do so, I can't further adjust the scores. There are no up or down arrows allowing me to adjust what the scores are. There is no way to adjust these numbers up or down on this page. If I disable manual entry and dice rolling (which is what I usually do!) then there is no way to adjust the numbers at all.
![image](https://github.com/user-attachments/assets/216a4ae1-25f6-4203-83c5-57ec33dd6b16)

**Comment by deciusaemilius** [comment]
If I switch back to version 1.4.1 it works correctly and the up/down arrows are there to be interacted with:
![image](https://github.com/user-attachments/assets/24ade569-ab8d-4d74-9e58-a494d6e17b10)

**Comment by geoidesic** [comment]
fixed in https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.4.5
