### ISSUE TITLE
### Bug Report: First Level Subclasses Not Adding

### ISSUE THREAD

**Issue by deciusaemilius** [geoidesic/foundryvtt-actor-studio#92]
Classes that get their subclasses at first level (Cleric, Sorcerer) aren't being correctly added to the character sheet
![image](https://github.com/user-attachments/assets/11f70299-ca13-40cb-9951-05a46f2b757f)

If I create a character with a different class, e.g. Paladin, that technically gets the subclass at 3rd level, it will "correctly" add it to the character sheet when chosen in Actor Studio. Even when, for example, Cleric domains are chosen, Actor Studio isn't adding them to the character sheet.

**Comment by geoidesic** [comment]
I’m sorry but I don’t understand what you are saying. What exactly is the problem?

**Comment by deciusaemilius** [comment]
Sure. Step 1: Create a Character. Select Cleric and a Subclass (Race and Background are irrelevant).
![image](https://github.com/user-attachments/assets/cdc136aa-bdf4-4aa4-9e4e-639509cff4d6)
![image](https://github.com/user-attachments/assets/37d66f13-9c01-468f-ae29-6c9916378284)
Step 2: Complete character selection and find the subclass has not been added:
![image](https://github.com/user-attachments/assets/3e05bdfa-a58a-44bd-906d-b435a50ad9cf)
If I then manually drag the Arcana domain from my Subclass compendium, it correctly adds:
![image](https://github.com/user-attachments/assets/b9bf3033-4cbf-4f92-8638-899b4fe0381b)


By contrast, if I create a paladin:
![image](https://github.com/user-attachments/assets/9bbc0519-9d28-4a96-b35f-a91d2612c4fb)
![image](https://github.com/user-attachments/assets/6fefd7ca-7276-426d-968d-794559633308)
The subclass correctly appears on the character sheet.

**Comment by geoidesic** [comment]
Where are you getting these subclasses from? They aren't part of SRD.
For me to trouble shoot them, you'd need to supply an export of that data, which you can do by importing the subclass to your game, then right-click on the subclass in the item tab of the side-bar and select export, then upload the file here.

Something to understand about how AS works – all it does is take your class / subclass / race / background from the compendium and drop it onto the character sheet. That's all. So if anything is going wrong in terms of what appears on the character sheet, that actually has nothing to do with AS – you'd get exactly the same result if you dropped the subclass onto the actor sheet manually.

I suggest you try that and see if you get a different result – try just drop the subclass on the sheet yourself directly from the compendium. If you get the same result, then there's nothing I can do to help you with that.

So I don't expect there will be anything I can do here. Most likely there's something wrong with the data source that you are using, or – less likely, a bug in the dnd5e foundryVTT system.

**Comment by deciusaemilius** [comment]
I switched solely to the SRD and this still happens.
![image](https://github.com/user-attachments/assets/2730d618-2626-42ae-bea5-72b76e8d2850)
![image](https://github.com/user-attachments/assets/76ef83b2-6689-44f0-b2dc-206872cda0ba)
![image](https://github.com/user-attachments/assets/bdee404d-6f36-465d-9b50-26cdd4900247)
![image](https://github.com/user-attachments/assets/b1574e3d-0f61-4f31-8a48-c65dd0799fbd)
![image](https://github.com/user-attachments/assets/d13579e3-e40a-4069-9fd0-cd411f34b016)

However, if I drop the subclass myself directly from the Compendium, it works correctly.
When I drag it directly from the Compendium I get a pop up box:
![image](https://github.com/user-attachments/assets/0a0ddb02-5f98-4c54-ba7c-00dcef0a8659)
And it then adds the subclass correctly:
![image](https://github.com/user-attachments/assets/c32d7911-944a-4601-855d-7dc63fc6e369)
This is not happening using Actor Studio.

**Comment by deciusaemilius** [comment]
This is also happening with the Sorcerer class (again, solely using the SRD):
![image](https://github.com/user-attachments/assets/b0be33f9-32cd-4984-a3cd-c7307631a939)
![image](https://github.com/user-attachments/assets/1dee2823-177e-4e67-9dab-7792e4ff4aeb)
Actor Studio isn't adding the subclass. If I manually drag the subclass from the SRD compendium, it adds correctly:
![image](https://github.com/user-attachments/assets/190ac41a-0523-4769-8485-826fbe81ee0c)
![Uploading image.png…]()

**Comment by geoidesic** [comment]
Fixed in https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.4.6

**Comment by geoidesic** [comment]
@deciusaemilius Thanks for all the precision in detail, this enabled me to find and squish the bug.
