### ISSUE TITLE
"weapos choose any 1"

### ISSUE THREAD

**Issue by Zarhog** [geoidesic/foundryvtt-actor-studio#93]
![image](https://github.com/user-attachments/assets/d7767fe1-aa75-4549-9a5c-748d12b86fdd)
lso i came across this small visual bug where its saying "weapos choose any 1" but the class is granting a specific list

**Comment by geoidesic** [comment]
@Zarhog Please can you export the class and upload it here? Or send it to me privately on Discord.

**Comment by Zarhog** [comment]
Sure

**Comment by Zarhog** [comment]
[fvtt-Item-pack-dnd5e-tcr-sub-class.json](https://github.com/user-attachments/files/16971402/fvtt-Item-pack-dnd5e-tcr-sub-class.json)
[fvtt-Item-pack-dnd5e-tcr-features-class.json](https://github.com/user-attachments/files/16971404/fvtt-Item-pack-dnd5e-tcr-features-class.json)
[fvtt-Item-pack-dnd5e-tcr-class.json](https://github.com/user-attachments/files/16971406/fvtt-Item-pack-dnd5e-tcr-class.json)

**Comment by Zarhog** [comment]
I recomend having the Class and class features compendium, so that the class points to the right items

**Comment by geoidesic** [comment]
hmm.. I couldn't make those work. I'm not sure what you mean by "having the Class and class features compendium" – do you mean the SRD compendiums? Or something else?

**Comment by Zarhog** [comment]
as for how to import the files i gave you use https://gitlab.com/mkahvi/fvtt-compendium-importer

**Comment by Zarhog** [comment]
Seems to be fixed
