### ISSUE TITLE
Advancement Window Not Closing on Character Creation

### ISSUE THREAD

**Issue by deciusaemilius** [geoidesic/foundryvtt-actor-studio#94]
Running Foundry 12.331, D&D 3.3.1. I have all modules disabled except for Actor Studio and I am using the SRD compendium. At the end of character creation, the advancement window does not close and character creation does not seem to be completed. Instead it ends up as a white box.
![image](https://github.com/user-attachments/assets/0f85faf4-bd4b-4542-ae6a-23bb1a09f955)

I have debug mode and extended debug mode turned on, I'm just not sure where to go to get the logs to upload.

When I reach the final advancement stage, whatever that is, I press the complete button:
![image](https://github.com/user-attachments/assets/b84b92ee-836b-4686-813b-5a52f49f9152)
and it immediately goes to this page:
![image](https://github.com/user-attachments/assets/c4aa431f-9ed9-44d5-9d44-6cc8a99afae8)

**Comment by geoidesic** [comment]
Hi. I can see you're using Ranger. 

1. Can you tell me what other selections you made please?
1. Is it only happening with Ranger?
1. What version of AS are you using?
1. What version of dnd5e are you using?
1. What version of foundryvtt are you using?

**Comment by deciusaemilius** [comment]
1. 
![image](https://github.com/user-attachments/assets/6c529bf9-b6ee-4472-9bb1-30d286095784)
![image](https://github.com/user-attachments/assets/a617d29c-fc71-4f0d-bf7d-a0fbd50b3b69)
![image](https://github.com/user-attachments/assets/4f6e67ec-bd88-482b-92cd-02962532b127)
![image](https://github.com/user-attachments/assets/3f7a90ff-edb9-4fab-8632-86d15056e11c)
Proficiencies/Skills were picked at random and seem to have no impact although I can specify choices if need be.
2. The problem happens with Barbarian, Bard, Druid, Fighter, Monk, Paladin, Ranger Rogue, and Wizard. 
Cleric, Sorcerer, Warlock work correctly.
2a. I have also tried switching races with Half Elf, Dragonborn, Dwarf and Human, no change.
3. Actor Studio 1.4.6
4. D&D 3.3.1
6. Foundry v12 Stable Build 331

**Comment by geoidesic** [comment]
> I have debug mode and extended debug mode turned on, I'm just not sure where to go to get the logs to upload.

On windows, hit F12
On Mac hit, OPTION + COMMAND + i

**Comment by geoidesic** [comment]
Fixed in https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.4.7
