### ISSUE TITLE
Races not appearing when inside Relivent Permission level folders

### ISSUE THREAD

**Issue by Zarhog** [geoidesic/foundryvtt-actor-studio#96]
will make git hub later but the Races are not showing up even though they are in the correct compendium and folder

![image](https://github.com/user-attachments/assets/7aea8a92-b38f-4656-98fa-dd7f7c19c50f)

**Comment by geoidesic** [comment]
Off the top of my head I don't think it supports subfolders in the permission folders. Can you try move human up a level so that it's just in the Member's folder directly?

**Comment by Zarhog** [comment]
This works in the Members folder directly. 

we had the same issue in testing when first making the modual with class. 

it would appear that calss and subclass was fixed to work, but Background and Race was not.

**Comment by geoidesic** [comment]
Yeah I think you are getting confused. I can't replicate this behaviour.

Subfolders within membership folders have never been supported. They don't work, not even for Class & Subclass. So is this a new feature request?

**Comment by geoidesic** [comment]
Unless I'm losing my marbles! I'll have another look later

**Comment by Zarhog** [comment]
??? i specifically remember having to have a long conversation when making the module as to why it was needed, and we even went over classes in particular. ???

**Comment by Zarhog** [comment]
if we dont have the modual also be able to seach subfolders ( and other folders under that) then it makes the managment of the compendiums that much harder.

**Comment by geoidesic** [comment]
I do vaguely remember this. Are you sure it’s working for classes and subclasses? I tried that this morning and it didn’t seem to be.

**Comment by geoidesic** [comment]
You haven't answered this question, so I'm going to make an assumption that they should be available to everyone.

**Comment by geoidesic** [comment]
I actually think you previously answered this question on Discord... this is the problem with posting it on Discord – it doesn't get tracked against the issue, so.... all those moments, will be lost in time, like tears, in rain...
