### ISSUE TITLE
Can't activate module. Max system version of 4, but my version is 4.0.0

### ISSUE THREAD

**Issue by zach-k0** [geoidesic/foundryvtt-actor-studio#98]
As the title says. I can't activate the module because it says system versions don't match, but they should be equivalent?

![image](https://github.com/user-attachments/assets/ab74d3a7-3f9d-4025-8f2b-3187afe83931)

**Comment by geoidesic** [comment]
fixed in https://github.com/geoidesic/foundryvtt-actor-studio/releases/tag/1.5.2
